Dev products
Almaz2312/selim pull request #1
Opened 2024-02-08 15:07 UTC by azamat-medenov

created endpoints for Product, Categories, Feedbacks

2024-02-09 15:08 UTC, Almaz2312 requested changes
Комеентарии по проделанной работе

2024-02-09 15:08 UTC, Almaz2312 commented on products/models.py
> +    type = models.CharField(max_length=255)
Для чего type нужен?

2024-02-09 15:08 UTC, Almaz2312 commented on products/models.py
> +    type = models.CharField(max_length=255)
Здесь для чего type нужен?

2024-02-09 15:08 UTC, Almaz2312 commented on products/serializers.py
> +    images = serializers.SerializerMethodField()
Можно тспользвать ProductImageSerializer вместо SerializerMethodField

2024-02-09 15:08 UTC, Almaz2312 commented on products/views.py
> +class ProductListView(APIView):
Почему на APIView,а не ListAPIView?
Если из-за филтрации, то используй django-filters

2024-02-09 15:08 UTC, Almaz2312 commented on tests/products/test_categories.py
> +    c = Category.objects.create(name="шлагбаум", description="test")
Для создания тестовых данных/объектов нужно сипользвать factory-boy. Для тебя будет проще в дальнейшем

2024-02-09 15:08 UTC, Almaz2312 commented on products/admin.py
> +
Нужно добавить админку. Добавление, изменение, удаление по крайней мере в начальной стадии будет в админке проходить

2024-02-09 15:08 UTC, Almaz2312 commented on products/admin.py
> +
Для удобства можно использовать инлайны (TabularInline/StackedInline)

2024-02-10 10:14 UTC, azamat-medenov commented on products/models.py
> +    type = models.CharField(max_length=255)
для обозначения имя категории

2024-02-10 10:14 UTC, azamat-medenov commented on products/models.py
> +    type = models.CharField(max_length=255)
для обозначения к какой продукции оставляется отзыв

2024-02-12 06:27 UTC, Almaz2312 commented on products/models.py
> +    type = models.CharField(max_length=255)
У тебя модель уже связана с категорией. Type не лишнее?

2024-02-12 06:28 UTC, Almaz2312 commented on products/models.py
> +    type = models.CharField(max_length=255)
Не лучше ForeignKey сделать на продукцию?

2024-02-15 12:23 UTC, azamat-medenov commented on products/models.py
> +    type = models.CharField(max_length=255)
у каждой категории могут быть свои подразделения, мы это в диаграмме указывали

2024-02-20 04:53 UTC, merged